export const CATEGORIES = {
  navigation:   'Navigation',
  layout:       'Layout',
  content:      'Content',
  forms:        'Forms',
  media:        'Media',
  feedback:     'Feedback',
};

export const COMPONENTS = {
  navbar: {
    name: 'Navigation Bar',
    also: ['Topnav', 'Header', 'Site Header', 'Global Nav'],
    desc: 'Horizontal bar at the top of every page. Orients users, hosts the logo, navigation links, and the primary CTA.',
    variants: ['Standard', 'Centered logo', 'Transparent overlay', 'Mega menu', 'Sticky / fixed', 'With utility bar'],
    tip: '"Add a sticky navbar: logo on the left, 4 nav links centered, and a filled CTA button on the right."',
    category: 'navigation',
  },
  logo: {
    name: 'Logo',
    also: ['Brand Mark', 'Brand Identity'],
    desc: 'The brand identifier. Can be an icon only (logomark), text only (wordmark), or both combined.',
    variants: ['Logomark + wordmark', 'Wordmark only', 'Icon only', 'Stacked', 'Horizontal'],
    tip: '"Place a horizontal logo (icon + brand name bold) top-left in the navbar, linking to the homepage."',
    category: 'navigation',
  },
  logomark: {
    name: 'Logomark',
    also: ['Brand Icon', 'Symbol', 'App Icon'],
    desc: 'The icon or graphic portion of a logo, used independently when the brand is already recognizable.',
    variants: ['Full color', 'Monochrome', 'Inverted', 'Square container', 'Circle container'],
    tip: '"Use a 32px logomark in the navbar. On mobile, hide the wordmark and keep only the logomark."',
    category: 'navigation',
  },
  wordmark: {
    name: 'Wordmark',
    also: ['Logotype', 'Brand Name Text'],
    desc: 'The text portion of a logo — the brand name in a specific typeface. Stands alone or pairs with the logomark.',
    variants: ['Regular weight', 'Bold', 'Custom lettering', 'Serif', 'All-caps'],
    tip: '"Add a semibold wordmark at 18–22px next to the logomark. Keep it in the brand primary color or white."',
    category: 'navigation',
  },
  'nav-link': {
    name: 'Navigation Link',
    also: ['Nav Item', 'Menu Item', 'Nav Tab'],
    desc: 'A clickable text link in the navbar routing users to a main section or page of the site.',
    variants: ['Plain text', 'With dropdown arrow', 'With icon', 'Active/current state', 'Underline indicator'],
    tip: '"Add 4 nav links: Features, Pricing, Docs, Blog. Show a bottom underline on the active page."',
    category: 'navigation',
  },
  hamburger: {
    name: 'Hamburger Menu',
    also: ['Mobile Menu Button', 'Nav Toggle', 'Three-line Menu'],
    desc: 'A button with three horizontal lines that shows/hides navigation on small screens. Hidden on desktop.',
    variants: ['3 lines', '3 dots (kebab)', 'Animated to X on open', 'With "Menu" label'],
    tip: '"Hide nav links on mobile and show a hamburger on the right. Clicking opens a full-height overlay menu."',
    category: 'navigation',
  },
  breadcrumb: {
    name: 'Breadcrumb',
    also: ['Breadcrumb Trail', 'Path Navigation'],
    desc: 'Secondary navigation showing the current location within the site hierarchy as a clickable trail.',
    variants: ['Slash separator', 'Arrow separator', 'With home icon', 'Schema.org structured data'],
    tip: '"Add a breadcrumb below the navbar: Home › Blog › Article Title. Make each ancestor a clickable link."',
    category: 'navigation',
  },
  footer: {
    name: 'Footer',
    also: ['Site Footer', 'Page Footer', 'Global Footer'],
    desc: 'The bottom section of every page. Contains secondary nav, legal links, social icons, and brand info.',
    variants: ['Minimal (copyright only)', 'Multi-column links', 'With newsletter signup', 'Dark / branded', 'Mega footer'],
    tip: '"Add a dark multi-column footer: logo + tagline left, 3 nav columns center, social icons and copyright bottom."',
    category: 'navigation',
  },
  'social-icons': {
    name: 'Social Icons',
    also: ['Social Links', 'Social Media Icons'],
    desc: 'A row of icon buttons linking to the brand\'s social media profiles. Usually in the footer or author bio.',
    variants: ['Icon only', 'Icon + label', 'Filled circles', 'Outlined', 'Monochrome grayscale'],
    tip: '"Add 4 social icon buttons: GitHub, Twitter/X, LinkedIn, YouTube. 24px icons, subtle hover opacity change."',
    category: 'navigation',
  },
  'sidebar-nav': {
    name: 'Sidebar Navigation',
    also: ['Side Nav', 'Vertical Nav', 'Left Nav', 'Dashboard Nav'],
    desc: 'Vertical navigation panel on the left side. Common in dashboards, admin panels, and docs sites.',
    variants: ['Full height', 'Collapsible (icon-only mode)', 'With sections/groups', 'With badge counts', 'With user profile at bottom'],
    tip: '"Add a 240px sidebar nav: grouped items with icons, active state highlighted, user profile pinned at the bottom."',
    category: 'navigation',
  },
  pagination: {
    name: 'Pagination',
    also: ['Page Numbers', 'Pager'],
    desc: 'Controls for navigating between pages of a content list or grid. Shows the current page and adjacent links.',
    variants: ['Numbered pages', 'Prev / Next only', 'With ellipsis', 'Load more button', 'Infinite scroll'],
    tip: '"Add centered pagination below the article grid: ← Prev, up to 7 page numbers with ellipsis, Next →."',
    category: 'navigation',
  },
  'tab-bar': {
    name: 'Tab Bar',
    also: ['Tabs', 'Tab Navigation', 'Tab Group'],
    desc: 'Horizontal row of tabs that switch between views within the same page. The active tab is visually distinguished.',
    variants: ['Underline style', 'Pill / filled style', 'Boxed', 'With icons', 'Vertical tabs', 'Scrollable on mobile'],
    tip: '"Add tabs below the page header: underline style, active tab in brand color with a 2px bottom border."',
    category: 'navigation',
  },
  'hero-section': {
    name: 'Hero Section',
    also: ['Above the Fold', 'Banner', 'Jumbotron'],
    desc: 'The first full-width section users see. Introduces the product, communicates value, and drives the primary conversion.',
    variants: ['Centered text', 'Split (text + image)', 'Full-bleed image', 'Video background', 'Animated illustration'],
    tip: '"Create a split-layout hero: value proposition headline left, product screenshot right. Subtle gradient background."',
    category: 'layout',
  },
  'section-header': {
    name: 'Section Header',
    also: ['Section Title', 'Block Header', 'Content Heading'],
    desc: 'A title and optional subtitle that introduce a content section. Usually centered, with a badge eyebrow above.',
    variants: ['Centered', 'Left-aligned', 'With badge eyebrow', 'With decorative line', 'Extra large'],
    tip: '"Use a centered section header: small badge eyebrow, large H2 title, 1–2 sentence description below in muted color."',
    category: 'layout',
  },
  card: {
    name: 'Card',
    also: ['Content Card', 'Tile', 'Panel'],
    desc: 'A self-contained UI container grouping related content. The fundamental building block for lists, grids, and dashboards.',
    variants: ['Default', 'Bordered', 'Elevated with shadow', 'Flat', 'Interactive / hoverable', 'Horizontal layout'],
    tip: '"Add a grid of cards: white background, 1px border, 8px radius, 24px padding, subtle box-shadow on hover."',
    category: 'layout',
  },
  divider: {
    name: 'Divider',
    also: ['Separator', 'Rule', 'Section Divider', 'HR'],
    desc: 'A horizontal line or visual break that separates sections of content or groups of elements.',
    variants: ['Plain line', 'With center text ("or")', 'With icon', 'Dashed', 'Thick / prominent'],
    tip: '"Add a divider with \'or\' text between social login buttons and the email form. Center text over a 1px line."',
    category: 'layout',
  },
  headline: {
    name: 'Headline',
    also: ['H1', 'Page Title', 'Hero Title', 'Main Heading'],
    desc: 'The largest text on the page. Communicates the core value proposition in 6–12 words. Usually the only H1.',
    variants: ['Single line', 'Two lines', 'Gradient text fill', 'With highlighted word', 'Animated word swap'],
    tip: '"Write a 2-line headline: bold first line states the benefit, second adds the differentiator. Use 48–64px, bold weight."',
    category: 'content',
  },
  subheadline: {
    name: 'Subheadline',
    also: ['Subtitle', 'Hero Description', 'Lead Text', 'Tagline'],
    desc: 'Supporting text below the headline. Expands on the value proposition in 1–3 sentences. Lighter weight, muted color.',
    variants: ['One sentence', 'Two sentences', 'Italic', 'Max-width constrained for readability'],
    tip: '"Add a 2-sentence subheadline: first explains what, second adds the key benefit. 16–20px, muted color."',
    category: 'content',
  },
  'cta-button': {
    name: 'CTA Button',
    also: ['Call-to-Action Button', 'Primary Button', 'Action Button'],
    desc: 'The main action button. High contrast, visually prominent, with a clear and specific action label.',
    variants: ['Filled / solid', 'Large hero size', 'With arrow icon', 'With loading spinner', 'Gradient fill'],
    tip: '"Add a large primary CTA: filled, high-contrast color, 44–48px height, label like \'Get started free →\'."',
    category: 'content',
  },
  'ghost-button': {
    name: 'Ghost Button',
    also: ['Outlined Button', 'Secondary Button', 'Stroke Button'],
    desc: 'A button with transparent fill and visible border. Used as a secondary action alongside a primary CTA.',
    variants: ['With border', 'Text-only (no border)', 'With icon', 'Same height as primary', 'Smaller'],
    tip: '"Pair a ghost button with the primary CTA: same height, transparent fill, 1px border. Label: \'See how it works\'."',
    category: 'content',
  },
  badge: {
    name: 'Badge',
    also: ['Label', 'Tag', 'Pill', 'Chip', 'Eyebrow Text'],
    desc: 'A small visual label highlighting a status, category, or promotion. Often above a headline to set context.',
    variants: ['Filled', 'Outlined', 'With dot indicator', 'With icon', 'Animated "new" state'],
    tip: '"Add a badge above the hero headline: small rounded pill, accent color, with a small emoji. Text like \'✦ New in 2025\'."',
    category: 'content',
  },
  'testimonial-card': {
    name: 'Testimonial Card',
    also: ['Review Card', 'Quote Card', 'Social Proof Card'],
    desc: 'A card displaying a customer quote, author name, company, and optional star rating. Builds trust.',
    variants: ['Quote + avatar', 'With star rating', 'Compact tweet-style', 'Large pull quote', 'Video thumbnail'],
    tip: '"Create a testimonial card: large open-quote mark, 2–3 sentence quote, then avatar + bold name + company below."',
    category: 'content',
  },
  'pricing-card': {
    name: 'Pricing Card',
    also: ['Plan Card', 'Pricing Tier', 'Subscription Card'],
    desc: 'A card showing a subscription plan: name, price, feature list, and a CTA. In a 2–4 column grid.',
    variants: ['Simple 3-tier', 'With "Most popular" badge', 'Monthly/annual toggle', 'With comparison table'],
    tip: '"Add 3 pricing cards: Free, Pro, Enterprise. Highlight the middle tier with a colored border and \'Most popular\' badge."',
    category: 'content',
  },
  'stat-block': {
    name: 'Stat Block',
    also: ['Metric Block', 'Key Number', 'Social Proof Stat'],
    desc: 'A bold number with a short label showcasing a key metric like active users, uptime, or integrations.',
    variants: ['Plain number + label', 'With icon', 'With trend indicator', 'Animated counter', 'Row of 4'],
    tip: '"Add a row of 4 stat blocks: large bold number, small descriptor label below. Use formats: 10K+, 99.9%, 150+."',
    category: 'content',
  },
  'team-card': {
    name: 'Team Member Card',
    also: ['Person Card', 'Profile Card', 'Bio Card'],
    desc: 'A card showcasing a team member: photo, name, title, optional bio, and social links.',
    variants: ['Photo + name + role', 'With bio text', 'With social links', 'Circular photo', 'Hover to reveal bio'],
    tip: '"Add a team grid with 4 cards per row: circular photo, bold name, role title in muted text, 3 social icon links."',
    category: 'content',
  },
  accordion: {
    name: 'Accordion',
    also: ['FAQ', 'Collapsible', 'Expandable Row', 'Disclosure'],
    desc: 'An interactive element that expands and collapses to reveal content. Used for FAQ sections.',
    variants: ['Single open at a time', 'Multiple open', 'With +/− icon', 'With chevron', 'Borderless / minimal'],
    tip: '"Add an FAQ accordion: each item has a question row that expands to show the answer. Chevron rotates 180° on open."',
    category: 'content',
  },
  'feature-card': {
    name: 'Feature Card',
    also: ['Feature Block', 'Value Prop Card', 'Feature Item'],
    desc: 'A card presenting one product feature with an icon, short title, and 1–2 sentence description.',
    variants: ['Icon on top', 'Horizontal (icon + text side by side)', 'With screenshot', 'With number', 'Bordered vs. flat'],
    tip: '"Create a 3-column feature grid. Each card: icon on top, bold title, 2-line description. Subtle border and hover lift."',
    category: 'content',
  },
  'article-card': {
    name: 'Article Card',
    also: ['Blog Card', 'Post Card', 'Content Preview Card'],
    desc: 'A card representing a blog post. Shows thumbnail, category, title, excerpt, author, and date.',
    variants: ['Vertical (image top)', 'Horizontal (image left)', 'Minimal (no image)', 'Featured (large)'],
    tip: '"Add article cards (3 columns): 16:9 thumbnail, category badge, H3 title, 2-line excerpt, author avatar + name + date."',
    category: 'content',
  },
  'project-card': {
    name: 'Project Card',
    also: ['Work Card', 'Portfolio Card', 'Case Study Card'],
    desc: 'A card showcasing a project with a preview image, title, tech stack tags, and links.',
    variants: ['With thumbnail', 'Hover overlay with links', 'With tech stack tags', 'Case study style'],
    tip: '"Add project cards in a 2-column grid: screenshot thumbnail, project name, 3 tech stack tag pills, links."',
    category: 'content',
  },
  'skill-tags': {
    name: 'Skill Tags',
    also: ['Tech Stack Tags', 'Technology Pills', 'Tag Cloud'],
    desc: 'A cluster of pill-shaped labels listing skills, technologies, or keywords. Grouped by category.',
    variants: ['Plain pills', 'Colored by category', 'With icons', 'With proficiency indicator', 'Grouped sections'],
    tip: '"Add a skill section: group by category (Languages, Frameworks, Tools). 28–32px pill height, 8px gap, muted border."',
    category: 'content',
  },
  timeline: {
    name: 'Timeline',
    also: ['Vertical Timeline', 'Experience Log', 'History'],
    desc: 'A vertical list of events or milestones ordered chronologically. Common in portfolio experience sections.',
    variants: ['Left-aligned', 'Alternating sides', 'Dot markers', 'Numbered', 'With company logos'],
    tip: '"Add a vertical timeline for work experience: company + role as H3, date range right-aligned, 2–3 bullet points each."',
    category: 'content',
  },
  'article-featured': {
    name: 'Featured Article',
    also: ['Hero Post', 'Lead Article', 'Featured Story'],
    desc: 'A larger, visually prominent card at the top of a blog. Bigger thumbnail, more prominent title and excerpt.',
    variants: ['Full-width image', 'Split layout (text + image)', 'With overlay text', 'With category + author + date'],
    tip: '"Add a featured post: 60% content + 40% thumbnail, H2 title, 2-line excerpt, author avatar + name + date."',
    category: 'content',
  },
  alert: {
    name: 'Alert',
    also: ['Notification Banner', 'Message Banner', 'Info Box', 'Flash Message'],
    desc: 'A full-width or inline message that draws attention to important information, warnings, errors, or success states.',
    variants: ['Success (green)', 'Error (red)', 'Warning (yellow)', 'Info (blue)', 'With dismiss button', 'With title + desc'],
    tip: '"Add a success alert: green left border, checkmark icon, short message, and an X dismiss button. Auto-dismiss after 4s."',
    category: 'feedback',
  },
  'data-table': {
    name: 'Data Table',
    also: ['Table', 'Grid', 'List View'],
    desc: 'A structured display of tabular data with rows, columns, headers, and optional sorting, filtering, and row actions.',
    variants: ['Basic', 'With sortable columns', 'With row actions', 'Striped rows', 'Compact / dense', 'With pagination footer'],
    tip: '"Add a data table: sticky header, alternating row colors, right-align numeric columns, icon-only action buttons per row."',
    category: 'feedback',
  },
  avatar: {
    name: 'Avatar',
    also: ['Profile Picture', 'User Photo', 'Profile Image'],
    desc: 'A circular or rounded image representing a person. Used in testimonials, comment threads, author bios, and team sections.',
    variants: ['Circle', 'Square rounded', 'With status dot', 'Initials fallback', 'Stacked group'],
    tip: '"Use a 40–48px circular avatar next to testimonial text. Add a 2px white ring and a 1px brand color border."',
    category: 'media',
  },
  'hero-image': {
    name: 'Hero Image',
    also: ['Hero Visual', 'Product Screenshot', 'Hero Illustration'],
    desc: 'The main visual in the hero section. Can be a product screenshot, illustration, photo, or abstract graphic.',
    variants: ['Product screenshot with browser chrome', 'Illustration', 'Photo', 'Abstract gradient', 'Floating UI chips'],
    tip: '"Place a product screenshot with subtle drop shadow in the hero. Slight tilt and floating UI chips for a 3D feel."',
    category: 'media',
  },
  'logo-bar': {
    name: 'Logo Bar',
    also: ['Social Proof Bar', 'Brand Logos', 'Customer Logos', 'Trust Strip'],
    desc: 'A horizontal row of company logos showing notable customers or integrations. Builds trust below the hero.',
    variants: ['Grayscale logos', 'Full-color logos', 'With "Trusted by" label', 'Scrolling marquee', 'Grid layout'],
    tip: '"Add a logo bar just below the hero: \'Trusted by teams at\' label, then 5–6 grayscale company logos spread evenly."',
    category: 'media',
  },
  thumbnail: {
    name: 'Thumbnail',
    also: ['Preview Image', 'Article Image', 'Card Image'],
    desc: 'A small preview image used in cards, lists, and grids to represent an article, product, or project.',
    variants: ['16:9 ratio', '4:3 ratio', 'Square (1:1)', 'With category badge overlay', 'With play button (video)'],
    tip: '"Add a 16:9 thumbnail at the top of each article card. Use object-fit: cover so it fills without distortion."',
    category: 'media',
  },
  form: {
    name: 'Form',
    also: ['Input Form', 'Data Entry Form', 'Contact Form'],
    desc: 'A structured group of input fields for collecting user data. Needs clear labels, validation, and a submit button.',
    variants: ['Contact form', 'Sign-up / registration', 'Login', 'Multi-step wizard', 'Inline single-field'],
    tip: '"Add a contact form: name, email, subject, message textarea, and a submit button. 16px vertical gap between fields."',
    category: 'forms',
  },
  'input-field': {
    name: 'Input Field',
    also: ['Text Input', 'Text Box', 'Form Field'],
    desc: 'A single-line text field for collecting short user input like a name, email, or search query.',
    variants: ['Default', 'With label above', 'With placeholder', 'With prefix/suffix icon', 'With validation error state'],
    tip: '"Add a labeled text input: label above, 40–44px height, 1px border, 6px radius. Red border + error message on invalid."',
    category: 'forms',
  },
  textarea: {
    name: 'Textarea',
    also: ['Multi-line Input', 'Text Area', 'Comment Box'],
    desc: 'A multi-line text field for longer input like messages, bios, or descriptions.',
    variants: ['Fixed height', 'Auto-grow with content', 'With character counter', 'Resizable handle'],
    tip: '"Add a message textarea: min-height 100–120px, same border style as text inputs. Character counter bottom-right."',
    category: 'forms',
  },
  'search-bar': {
    name: 'Search Bar',
    also: ['Search Input', 'Search Box', 'Search Field'],
    desc: 'A prominently styled input for searching content. Usually includes a magnifier icon and optional clear button.',
    variants: ['Inline in navbar', 'Full-width below nav', 'With autocomplete dropdown', 'With filter chips', 'Expandable'],
    tip: '"Add a search bar in the navbar: expandable, magnifier icon on the left. On mobile, show icon-only that expands on tap."',
    category: 'forms',
  },
  'select-field': {
    name: 'Select / Dropdown',
    also: ['Dropdown', 'Select Input', 'Combobox'],
    desc: 'A form control for selecting one option from a predefined list. Shows a native or custom-styled dropdown.',
    variants: ['Native select', 'Custom styled', 'Searchable (combobox)', 'Multi-select', 'With option groups'],
    tip: '"Use a select for 5+ options. For 2–4 options, prefer radio buttons. For many options with search, use a combobox."',
    category: 'forms',
  },
  'toggle-switch': {
    name: 'Toggle Switch',
    also: ['Switch', 'Toggle', 'On/Off Switch'],
    desc: 'A binary control that switches between on and off states. Cleaner than a checkbox for settings and preferences.',
    variants: ['Default size', 'Small', 'Large', 'With label left', 'With label right', 'Disabled state'],
    tip: '"Use a toggle switch for settings (not checkboxes). Label on the right, 36px width, green when active, gray when off."',
    category: 'forms',
  },
  checkbox: {
    name: 'Checkbox',
    also: ['Checkbox Input', 'Multi-select Control'],
    desc: 'A binary input allowing users to select or deselect an option independently. Use for multi-select or agreement prompts.',
    variants: ['Default', 'Checked', 'Indeterminate', 'With label', 'Card checkbox', 'Disabled'],
    tip: '"Add checkboxes for multi-select lists. Label always on the right, 16px size, brand color when checked."',
    category: 'forms',
  },
};

// Which components appear in each layout (determines browser list)
export const LAYOUT_COMPONENTS = {
  landing:   ['navbar','logo','logomark','wordmark','nav-link','cta-button','ghost-button','hamburger','hero-section','badge','headline','subheadline','hero-image','logo-bar','section-header','feature-card','stat-block','testimonial-card','avatar','pricing-card','accordion','footer','social-icons'],
  corporate: ['navbar','logo','logomark','wordmark','nav-link','cta-button','ghost-button','hamburger','breadcrumb','hero-section','headline','subheadline','hero-image','stat-block','feature-card','section-header','team-card','avatar','form','input-field','textarea','sidebar-nav','footer','social-icons'],
  startup:   ['navbar','logo','logomark','wordmark','nav-link','cta-button','ghost-button','hamburger','hero-section','badge','headline','subheadline','hero-image','logo-bar','section-header','feature-card','pricing-card','stat-block','footer','social-icons'],
  portfolio: ['navbar','logo','wordmark','nav-link','cta-button','hero-section','badge','headline','subheadline','avatar','social-icons','skill-tags','project-card','thumbnail','timeline','footer'],
  blog:      ['navbar','logo','logomark','wordmark','nav-link','search-bar','cta-button','hamburger','breadcrumb','article-featured','badge','headline','subheadline','thumbnail','avatar','section-header','article-card','pagination','footer','social-icons'],
  components: ['navbar','logo','sidebar-nav','breadcrumb','tab-bar','cta-button','ghost-button','badge','alert','section-header','input-field','select-field','textarea','toggle-switch','checkbox','card','data-table','divider','pagination','feature-card'],
  login:     ['logo','logomark','wordmark','headline','subheadline','cta-button','ghost-button','input-field','form','divider'],
};

export const LAYOUTS = [
  { id: 'landing',    label: 'Landing Page' },
  { id: 'corporate',  label: 'Corporate' },
  { id: 'startup',    label: 'Startup' },
  { id: 'portfolio',  label: 'Portfolio' },
  { id: 'blog',       label: 'Blog' },
  { id: 'components', label: 'Component Library' },
  { id: 'login',      label: 'Login Page' },
];

export const HERO_BACKGROUNDS = [
  { id: 'solid',         label: 'Solid',      swatch: '#f9fafb' },
  { id: 'gradient-1',    label: 'Purple',     swatch: 'linear-gradient(135deg,#667eea,#764ba2)' },
  { id: 'gradient-2',    label: 'Ocean',      swatch: 'linear-gradient(135deg,#0ea5e9,#10b981)' },
  { id: 'gradient-3',    label: 'Sunset',     swatch: 'linear-gradient(135deg,#f97316,#ec4899)' },
  { id: 'gradient-4',    label: 'Night',      swatch: 'linear-gradient(135deg,#1e293b,#0f172a)' },
  { id: 'pattern-dots',  label: 'Dots',       swatch: '#fff' },
  { id: 'pattern-lines', label: 'Lines',      swatch: '#f3f4f6' },
  { id: 'image',         label: 'Photo',      swatch: 'url(dummy-image.png)' },
];
